site_name: mion docs
repo_url: https://github.com/NetworkGradeLinux/mion/
site_description: Documentation for Network Grade Linux mion
edit_uri: ""

remote_branch: gh-pages
remote_name: dunfell

nav:
  - Home: index.md
  - Getting Started Guide: getting-started.md
  - Installing mion: installing_mion.md
  - Supported Switches: supported-switches.md
  - Resources: resources.md
  - mion Container Support: mion-container-support.md
  - Stratum: stratum.md
  - Glossary: glossary.md
  - Adds and Ends: adds-and-ends.md
  - Release Notes: 
      - 2021.03: release_notes/2021-03.md
  - Accessibility: ACCESSIBILITY.md
  - Community:
      - About our Community: community/Community.md
      - Code of Conduct: community/code-of-conduct.md
      - CoC Interpretation: community/Coc-interpretation.md
  - Adds and Ends: adds-and-ends.md
  - Acknowedgements: acknowledgements.md

# Theme settings
theme:
    name: material
    scheme: mion
    features:
      #custom_dir: overrides
    logo: assets/images/mion-colour-small.png

      #extra_css:
      #  - stylesheets/color_schemes/mion.css
extra_css:
  - stylesheets/extra.css
# add attribute list extension to allow for html/CSS  for markdown elements,
# primarily to allow for image sizing and alignment
  - css/version-select.css
markdown_extensions:
  - attr_list

# Versioning done with https://github.comjimporter/mike
extra_javascript:
  - js/version-select.js

extra:
    version:
        method: mike
