site_name: mion docs
repo_url: https://github.com/NetworkGradeLinux/mion/
site_description: Documentation for Network Grade Linux mion

# this may need changing...  
remote_branch: gh-pages
remote_name: dunfell

nav:
  - Home: index.md
  - Getting Started Guide: getting-started.md
  - Installing mion: installing_mion.md
  - Resources: resources.md
  - Image Types: imagetypes.md
  - Trusted Platform Module: trusted-platform-module.md
  - Glossary: glossary.md
  - Accessibility: ACCESSIBILITY.md
  - Community:
      - About our Community: community/Community.md
      - Code of Conduct: community/code-of-conduct.md
      - CoC Interpretation: community/Coc-interpretation.md
  - Acknowedgements: acknowledgements.md


# Theme settings
theme:
    name: material
    scheme: mion
      #custom_dir: overrides
    logo: assets/images/mion-colour-small.png

      #extra_css:
      #  - stylesheets/color_schemes/mion.css
extra_css:
  - stylesheets/extra.css
# add attribute list extension to allow for html/CSS  for markdown elements,
# primarily to allow for image sizing and alignment
  - css/version-select.css
markdown_extensions:
  - attr_list

# Versioning done with https://github.comjimporter/mike
#plugins:
#  - mike:
#      version_selector: true
#      css_dir: css
#      javascript_dir: js
extra_javascript:
  - js/version-select.js

extra:
    version:
        method: mike
